# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27e2e0f8b353aec673486ea321cb941bd78f5c79959360e783a56fca9b84e50983b65fe3d7324db0b9b2e33424b4cb7e550b78190b806437d18920b88ae442dc

test:
  secret_key_base: 992a3d9b4c445eca289c8fb0d92c111e031ea110a9005e00d5b6e51bde8c58ecb0de239c7d7e9178d4477c65b7bd2baa462f18b02454da1530c66a8b77f10841

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
